using Ember.Bot.Modules;
using FluentAssertions;

namespace Ember.Tests;

/// <summary>
/// Verifies the custom ID contracts between HabitSelectModule (producers)
/// and HabitActionModule / ReminderSetupModule (consumers).
///
/// These tests don't spin up Discord — they assert that the ID strings
/// generated by the select handlers match the ComponentInteraction attribute
/// patterns registered on the button/modal handlers.
/// </summary>
public class HabitSelectRoutingTests
{
    // ─────────────────────────────────────────────────────────────────────────
    // Checkin route: habit:select:checkin → habitaction:checkin:done:* / skip:*
    // ─────────────────────────────────────────────────────────────────────────

    [Fact]
    public void CheckinRoute_DoneButtonId_MatchesHandlerPattern()
    {
        var habitId = 42;
        var buttonId = $"habitaction:checkin:done:{habitId}";

        // Must match [ComponentInteraction("habitaction:checkin:done:*")]
        buttonId.Should().StartWith("habitaction:checkin:done:");
        buttonId.Should().EndWith(habitId.ToString());
    }

    [Fact]
    public void CheckinRoute_SkipButtonId_MatchesHandlerPattern()
    {
        var habitId = 42;
        var buttonId = $"habitaction:checkin:skip:{habitId}";

        // Must match [ComponentInteraction("habitaction:checkin:skip:*")]
        buttonId.Should().StartWith("habitaction:checkin:skip:");
        buttonId.Should().EndWith(habitId.ToString());
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Delete route: habit:select:delete → habitaction:delete:confirm:* / cancel
    // ─────────────────────────────────────────────────────────────────────────

    [Fact]
    public void DeleteRoute_ConfirmButtonId_MatchesHandlerPattern()
    {
        var habitId = 7;
        var buttonId = $"habitaction:delete:confirm:{habitId}";

        buttonId.Should().StartWith("habitaction:delete:confirm:");
        buttonId.Should().EndWith(habitId.ToString());
    }

    [Fact]
    public void DeleteRoute_CancelButtonId_IsLiteral()
    {
        // Cancel has no habitId — it's a literal ID
        var buttonId = "habitaction:delete:cancel";
        buttonId.Should().Be("habitaction:delete:cancel");
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Edit route: habit:select:edit → habitaction:edit:rename:* / reminder:set:* /
    //             reminder:clear:* / reminder:cancel:*
    // ─────────────────────────────────────────────────────────────────────────

    [Theory]
    [InlineData("habitaction:edit:rename:")]
    [InlineData("reminder:set:")]
    [InlineData("reminder:clear:")]
    [InlineData("reminder:cancel:")]
    public void EditRoute_ButtonIds_HaveCorrectPrefix(string expectedPrefix)
    {
        var habitId = 5;
        var buttonId = $"{expectedPrefix}{habitId}";

        buttonId.Should().StartWith(expectedPrefix);
        buttonId.Should().EndWith(habitId.ToString());
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Pause route: habit:select:pause → habitaction:pause:{habitId}:{duration}
    // ─────────────────────────────────────────────────────────────────────────

    [Theory]
    [InlineData("today")]
    [InlineData("3days")]
    [InlineData("1week")]
    [InlineData("resume")]
    public void PauseRoute_AllDurations_ProduceValidIds(string duration)
    {
        var habitId = 3;
        var buttonId = $"habitaction:pause:{habitId}:{duration}";

        // Must match [ComponentInteraction("habitaction:pause:*:*")]
        buttonId.Should().StartWith("habitaction:pause:");

        var parts = buttonId.Split(':');
        parts.Should().HaveCount(4);
        parts[2].Should().Be(habitId.ToString());
        parts[3].Should().Be(duration);
    }

    [Fact]
    public void PauseRoute_DurationParsing_RejectsUnknownDuration()
    {
        // The handler uses a switch expression; unknown durations fall back to 1week.
        // This test documents the fallback contract.
        var knownDurations = new[] { "today", "3days", "1week", "resume" };
        var testDuration = "unknown";
        knownDurations.Should().NotContain(testDuration,
            "unknown durations fall through to a 1-week default in OnPauseAsync — document this");
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Frequency route: habit:select:frequency → habitaction:freq:{id}:daily /
    //                                           freq:weekly:{id}:{target}
    // ─────────────────────────────────────────────────────────────────────────

    [Fact]
    public void FrequencyRoute_DailyButtonId_MatchesHandlerPattern()
    {
        var habitId = 11;
        var buttonId = $"habitaction:freq:{habitId}:daily";

        // Must match [ComponentInteraction("habitaction:freq:*:*")] — literal suffix after * not supported by Discord.Net
        var parts = buttonId.Split(':');
        parts.Should().HaveCount(4);
        parts[0].Should().Be("habitaction");
        parts[1].Should().Be("freq");
        parts[3].Should().Be("daily");
    }

    [Theory]
    [InlineData(1)]
    [InlineData(2)]
    [InlineData(3)]
    [InlineData(4)]
    [InlineData(5)]
    [InlineData(6)]
    public void FrequencyRoute_WeeklyButtonIds_HaveCorrectFormat(int target)
    {
        var habitId = 11;
        var buttonId = $"freq:weekly:{habitId}:{target}";

        // Must match [ComponentInteraction("freq:weekly:*:*")] in FrequencyButtonModule
        var parts = buttonId.Split(':');
        parts.Should().HaveCount(4);
        parts[0].Should().Be("freq");
        parts[1].Should().Be("weekly");
        parts[2].Should().Be(habitId.ToString());
        int.Parse(parts[3]).Should().BeInRange(1, 6);
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Rename modal: habitaction:edit:rename:* → habit:rename:modal:*:* (with messageId)
    // ─────────────────────────────────────────────────────────────────────────

    [Fact]
    public void RenameModal_CustomId_IncludesBothHabitIdAndMessageId()
    {
        var habitIdStr  = "42";
        var messageId   = 99999999999999999UL;
        var customId    = $"habit:rename:modal:{habitIdStr}:{messageId}";

        // Must match [ModalInteraction("habit:rename:modal:*:*")]
        var parts = customId.Split(':');
        parts.Should().HaveCount(5);
        parts[0].Should().Be("habit");
        parts[1].Should().Be("rename");
        parts[2].Should().Be("modal");
        parts[3].Should().Be(habitIdStr);
        ulong.TryParse(parts[4], out _).Should().BeTrue("message ID must be a valid ulong");
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Grace route: /habit grace → habit:grace:{0-3}
    // ─────────────────────────────────────────────────────────────────────────

    [Theory]
    [InlineData(0)]
    [InlineData(1)]
    [InlineData(2)]
    [InlineData(3)]
    public void GraceRoute_ButtonIds_AreInValidRange(int days)
    {
        var buttonId = $"habit:grace:{days}";

        // Must match [ComponentInteraction("habit:grace:*")]
        buttonId.Should().StartWith("habit:grace:");
        int.TryParse(buttonId.Split(':')[2], out var parsed).Should().BeTrue();
        parsed.Should().BeInRange(0, 3);
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Leaderboard opt-out button
    // ─────────────────────────────────────────────────────────────────────────

    [Fact]
    public void LeaderboardOptOutButton_HasLiteralId()
    {
        var buttonId = "leaderboard:optout";
        // Must match [ComponentInteraction("leaderboard:optout")]
        buttonId.Should().Be("leaderboard:optout");
    }
}
